version: '3'

services:
  n8n:
    image: your-image-name
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data:/data
      - ./n8n-scripts:/data/scripts
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
